import type { Metadata } from "next";
import { Geist, Geist_Mono, PT_Serif} from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const ptSerif = PT_Serif({
  variable: "--font-pt-serif",
  weight: ["400","700"],
  subsets: ["latin"],
  display: "swap",
})

export const metadata: Metadata = {
  title: "Amrithakesham",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html 
    lang="en"
    className={`
        ${geistSans.variable}
        ${geistMono.variable}
        ${ptSerif.variable}
      `}>
      <head>
        <link rel="icon" type="image/png" href="/image.png?v=1" />
        <link rel="shortcut icon" href="/image.png?v=1" />
        <link rel="apple-touch-icon" href="/image.png?v=1" />
      </head>
      <body
        className="antialiased font-sans"
      >
        {children}
      </body>
    </html>
  );
}
